server:
  port: 9090

spring:
  application:
    name: billing-notification
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/billing_notification?allowPublicKeyRetrieval=true&useSSL=false&SslMode=DISABLED
    username: root
    password: billing@123
